-- ============================================================
--  Manawa Review — Import data tenant SRL dari Google Form
--  Digenerate 2026-06-15 09:27 dari spreadsheet pendaftaran.
--  - 79 tenant unik (dedup per NIM ketua, submission terakhir menang).
--  - Password penjual = NIM ketua tim (disimpan sbg bcrypt hash).
--  - Password admin   = 'adminmanawa'.
--  - berkas_url = link Google Drive PDF dari kolom 'Lampirkan berkas'.
-- ============================================================
USE manawa_review;

-- Kolom tambahan utk lampiran & logo (aman dijalankan berulang).
ALTER TABLE tenant
  ADD COLUMN IF NOT EXISTS berkas_url VARCHAR(255) DEFAULT NULL AFTER spot,
  ADD COLUMN IF NOT EXISTS logo_url   VARCHAR(255) DEFAULT NULL AFTER berkas_url;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE review;
DELETE FROM akun WHERE peran = 'penjual';
TRUNCATE TABLE tenant;
SET FOREIGN_KEY_CHECKS = 1;

-- ---- Tenant ----
INSERT INTO tenant (slug, nama_bisnis, nama_ketua, email, tipe, spot, berkas_url) VALUES
  ('bilbo-lapis-susu', 'Bilbo Lapis Susu', 'Salsabilla Febrihesna', 'salsabilla.febrihesna@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1Pv5W_SrhWPWsSKou_jMVXi0M-rHIR6N2/view'),
  ('littleouch', 'littleouch', 'VERENT APRILLIA YOHAN', 'verent.yohan@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1NOR4GvLA9FsKzaHc4kIySe-3H_pygqD6/view'),
  ('fat-al-s-hotdog', 'Fat Al\'s Hotdog', 'Shakila Niswah Yuflih Dewi', 'shakila.dewi@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1WzxlJ1Jz_V-fKMI302K52dED_1fGMKhh/view'),
  ('wesley-s-heart', 'Wesley\'s Heart', 'Akhila Fathi Abdillah Luqman', 'akhila.luqman@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/11DatJdvvifXrhPJdEXNnlW0S8FvHPYXt/view'),
  ('zelv-re', 'zelvère', 'zelfi sinta karnilah', 'zelfi.karnilah@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1QeAWr-GC_q1E87lOVXzp6ep0RcuydWrk/view'),
  ('kopi-jiwapat', 'Kopi Jiwapat', 'Kevin Dwinata Hadiyan', 'kevin.hadiyan@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1XMsbGDfKHZfe3eKtv403q8kd0Mhlyvcs/view'),
  ('chrome-petal', 'Chrome Petal', 'Azkiya Nazillia Rabbani', 'azkiya.rabbani@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1_DKLhSfMdqF1s-tQ5NMpBqE4AnklqSlu/view'),
  ('fresh-laundry', 'Fresh laundry', 'Jessica Kezia Effendy', 'jessica.effendy@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1w6aC73k6P_NymiJ_8MB3Nr1L2gjZBbCP/view'),
  ('daintsy', 'Daintsy', 'Bidara Rahma Shabira', 'bidara.shabira@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/10p5u4psAYRcfrtZjhyUCqi-gMN54enW8/view'),
  ('moozy-wear', 'Moozy Wear', 'Fayne Nayata Firdaus', 'fayne.firdaus@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1TcVBsyvRwBIr3XBFEwGQHFK7DTXb7bnE/view'),
  ('so-cool-style', 'So Cool Style', 'Michellie Kwa', 'michellie.kwa@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/16D_HrPDpuB-o7_gcB7e9-6fX8NUAYiMh/view'),
  ('bites-and-drinks', 'bites and drinks', 'maria adriellia', 'maria.adriellia@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/13oBqMvLTnBr26Cz14trYZC0ltz2oosg9/view'),
  ('zavio', 'zavio', 'Elizabeth Jacelyn Rikiyanto', 'elizabeth.rikiyanto@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1l-t2ICUgUjNNB8dUdc5GoHRADO6sSMMG/view'),
  ('bloobub', 'bloobub', 'Ayesha Raya Raditya', 'ayesha.raditya@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/14Z04ypW3490YS-ehcysPXGeKA-EH0nAR/view'),
  ('cabi', 'Cabi', 'Alicia Orell Mulijadi', 'alicia.mulijadi@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1mrLdfnZ68fVgCjPTso_CpmfzfGqUyWUs/view'),
  ('seblak-makwiee', 'Seblak Makwiee', 'Renata Indah Supriadi', 'renata.supriadi@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1M90HyrIWoOsndI2MMCvgQV1lMvGJhM6K/view'),
  ('mushimushi-studio', 'Mushimushi Studio', 'Clariszya Vanessa Putri Alexandria', 'clariszya.alexandria@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1wU_StlfMsAu8CwbJcx6tTHzQ4zbkeEMp/view'),
  ('suddenim', 'SUDDENIM', 'Raihan Rizky Al-Farizi', 'raihan.alfarizi@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1pcYH6EEpRiSgK3tOg9NF_XpF2a4P5KBN/view'),
  ('krazzie', 'KRAZZIE', 'Amelia Sharon Lembong', 'amelia.lembong@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1cYwDUOdcAk4XndLsfoOhsY51fIqxQvKg/view'),
  ('kanal', 'Kanal', 'Verril Qabil', 'verrill.qabil@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1KgXpcbBC-6ZPWUTDLyLpO0D49V7V0aMd/view'),
  ('whippory', 'Whippory', 'Tatsbita Putri Nabila', 'tatsbita.nabila@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1vaPSN4AjU7DuT-RQK9fgvh4hyO_ajuNc/view'),
  ('beruma-lab-pergantian-dari-army-coffee', 'Beruma Lab (pergantian dari Army Coffee)', 'Jeannifer Dejella Navaky Kengsiswojo', 'jeannifer.kengsiswojo@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/19XKBqM73tawW1KrBy87K8_RnZAJUyqiC/view'),
  ('geprek', 'Geprek', 'Stephanie', 'stephanie.sukmajaya@bi nus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1wJp4ZtGNrwam2g5j-0cEnC51C7uimRbR/view'),
  ('gojie', 'GOJIE', 'Zahran Fawwaz Alfadhil', 'Zahran.alfadhil@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1OQuApEqMj3iESU580KBx7SsjfIPSd0nF/view'),
  ('nexo-sporty', 'Nexo Sporty', 'Velicia Widjaja', 'velicia.widjaja001@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1JDKvzyyV-fZgKVde1X2GIFx8tFqczRp5/view'),
  ('fruizzy', 'Fruizzy', 'Mischa Karin Tjhan Karaseran', 'mischa.karaseran@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1RnHb-9JkjtPU1o4jQrAO6cGEMvlro3K3/view'),
  ('neff-footwear', 'Neff footwear', 'Muhammad Farhan Fauzan Latif', 'muhammad.latif@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1u4EuDlVY7_LngDMFBNKTDhFqXGSJi7ON/view'),
  ('sandwichu', 'SANDWICHU', 'William Hartono', 'william.hartono001@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1FdTm9LCCAC8sIIPSxPia5HjR9-8ZB5L6/view'),
  ('doudonails', 'doudonails', 'Theresia Catherine Sugiwan', 'theresia.sugiwan@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1ZTvHVYIT2Uv7sNyEOeqvKEOu8n6md88O/view'),
  ('semara', 'SEMARA', 'Albertus Batya Evotianus', 'albertus.evotianus@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1hDVm7hgMezOCB4BP7_rIMwNua-qv_bBz/view'),
  ('icarus', 'ICARUS', 'Muhammad Sakhi Maisan', 'muhammad.maisan@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1Eqr7ng8Zybzm0K-QITU9VDcfLxPv8vZI/view'),
  ('satis', 'Satis', 'Aura Zahra Junia', 'aura.junia@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1-g_D5qV38sd9kKhsRLiMOVEBJs2Zw_7M/view'),
  ('rebiko', 'Rebiko', 'Annisa Rachma Khamilla', 'annisa.khamilla@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1Qv1PaMyoR2yBX0Fq5O8GKlxqthe8akbw/view'),
  ('sai', 'SAI', 'Farrel Catra Athallah', 'farrel.athallah@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1UHWrUXC8S7EtoU4xseWriO28RAbmgirm/view'),
  ('kripcau-chips', 'Kripcau Chips', 'Farel Muhammad Arrasyid', 'farel.arrasyid@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1VGRBraV-gWCL_14RUFkcRc352NSDqbqg/view'),
  ('reactive', 'ReActive', 'Irsyal Fauzan Sanad', 'irsyal.sanad@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1p7F4m0uZyWnqqE7JyWkO3E3mfW6sojlU/view'),
  ('sweetmissu', 'sweetmissu', 'okcta aurelia regina', 'Okcta.regina@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1BAl0QhSo_4XRKcKFFTzGFrgdt0vrN6VU/view'),
  ('june-de-belle', 'June de Belle', 'Mayra Ayaka', 'mayra.ayaka@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1N9dppGIFiPAlvb_mzvi_aSxPScV2-4Jh/view'),
  ('love-live-cake', 'Love Live Cake', 'Sivani Salsabbillah', 'sivani.salsabbillah@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1rC6eJlOZnP_QPseSowuaLKPQZ783vXLI/view'),
  ('trinket-tales', 'Trinket Tales', 'Fairuz', 'fairuz@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1Z6Ws6o30c9-EA8NMWMh_PtvqCRofQO1b/view'),
  ('navie-house', 'Navie House', 'Muhammad Daffa Qurrata Aiba', 'muhammad.aiba@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1pIdBXQeF3rZ795qStZD2CUgqVXUOuNEl/view'),
  ('sinergi-lestari-mandiri', 'Sinergi Lestari Mandiri', 'Muhammad Rafi Ulya', 'muhammad.ulya@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1d6jYUA_tvVrjufwLsch4h41hxqoqPLMA/view'),
  ('luthena', 'Luthena', 'Lusiana Devi', 'lusiana.devi@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1GfYgBG_sTshq40jV18-ZlMj8UpiQ53EN/view'),
  ('ego-apparel', 'EGO Apparel', 'Mohammad Farrel Abrar Gunawan', 'mohammad.gunawan@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1WoXZfHRdEJoaDo_vTnhQM5_mx-iZwkmN/view'),
  ('pallas-seafood', 'Pallas Seafood', 'Muadz Aladaalah', 'muhammad.aladaalah@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1wiN6SDVjGD_GhsFsqU5Qt5TnFIuG_B7R/view'),
  ('chuwink', 'Chuwink', 'Sharon Natasha Hutany', 'sharon.hutany@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1FeDtKKeXqqHpvYtKg1QgOwB9dDR7zGDZ/view'),
  ('kriuk-lembu-indonesia', 'Kriuk Lembu Indonesia', 'Naufal Ghazi Da\'is Annabil', 'Naufal.annabil@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1N-NqdTe1Zoh1VQlEYQ-_cP5arqqbT3C-/view'),
  ('milzy', 'MILZY', 'Shofa Marsandra', 'shofa.marsandra@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1Ve80wSFqfq2-yJaVTVoOajiAZasBmM1g/view'),
  ('macs', 'MACs', 'Moses Rafael Amadeus', 'moses.amadeus@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1vVU2e4Rh0AtnhO53ai0WKmEKz_Pddqb4/view'),
  ('chomped', 'Chomped', 'Nashella Fachira Hanzani', 'nashella.hanzani@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/10mnA1syAu7EYC66Rzcc4RfiW6DzXd8hW/view'),
  ('altek-industries', 'ALTEK INDUSTRIES', 'Aedil Hamdallah Ismail', 'aedil.ismail@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1gtUcVnn39puUisdEKOS_PgetP4Yewj9z/view'),
  ('the-bliss-c', 'The Bliss C.', 'Darius Hosea', 'darius.hosea@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1LURJnbokm9-wvTVBT8qL3S4rRIOd_IUY/view'),
  ('onzen', 'Onzen', 'Michelle Louisa', 'michelle.louisa@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1S84vuNYoBezbBxFKimAbYeFJqTDIldDc/view'),
  ('kiisover', 'Kiisover', 'Aliyaa Raisa Adzany', 'aliyaa.adzany@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1mifjumZ7H2RG_JE_DG3n8CozhholXpK4/view'),
  ('k-r-i-k', 'k r i k.', 'Caroline Kurniawan', 'caroline.kurniawan@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1kzYK0rJhWMDfg-Ti1x4YEJ3NZ-KcMU4h/view'),
  ('backthen', 'BACKTHEN', 'Faiza Himatul Aliyah', 'faiza.aliyah@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1ZI-anyk1Ds7CuaketCAyNB80QAtQHBqj/view'),
  ('flor-de-piel', 'FLOR de PIEL', 'IFAN MAULANA', 'ifan.maulana@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1Rrlp8xjL89Wi5VUCYOQjF3N5WZ9f3TaD/view'),
  ('aurelune', 'Aurelune', 'Ariffin Hermawan', 'Ariffin.hermawan@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1XOYaiBUCsj9SRUBd9prKC-gYpDkCkSv8/view'),
  ('brewchill', 'Brewchill', 'Calvin varelly', 'calvin.varelly@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1OJjry7vyQihQhLHBA-zj5MUm-aThhmkL/view'),
  ('freddo', 'Freddo', 'Michael Nathaniel Suteja', 'michael.suteja@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1j2ziXYotkDk3SNfv7cC4rSOcgImuwHKT/view'),
  ('mingcase-official', 'MINGCASE OFFICIAL', 'Louise Lawrence Setiahardi', 'louise.setiahardi@binuus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1hHDPyGBOUKawaD9hR-Fg8E2srbyV5cU1/view'),
  ('creacy-studio', 'Creacy Studio', 'Nazwa Gizara Inesita', 'nazwa.inesita@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1ymrlGlllXw6dHYBI0V-rpnBl3QhLZAEg/view'),
  ('sister-english', 'Sister English', 'Widia Kholifatus Sholikha', 'widia.sholikha@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1oYq5gOyumY0aidG_ARATGgTii5X-0Vku/view'),
  ('pollospok', 'PollosPok', 'Sean Felix Eros', 'sean.eros@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1L7kxGBMURy4w3_qLJMV3zx2iCIbJ61tE/view'),
  ('sera-coffee', 'SERA COFFEE', 'Reyhaq Muluk', 'reyhaq.muluk@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1BAAsJCxccNpzBwH93A4-plYwGnNaQWzt/view'),
  ('si-madu-koh-siu', 'Si Madu & Koh Siu', 'Kent Zhenoe', 'kent.zhenoe@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1fsqpSo4MhqI3r6MDPdzxlQEjyxFRrMRv/view'),
  ('milky-mood', 'Milky Mood', 'Delroy Jefferson', 'delroy.jefferson@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1482VdgpTEx7dUIwG7YyNv6GEtJLtKs4k/view'),
  ('harb-coffee', 'Harb Coffee', 'Marcel Christa Silap', 'marcel.silap@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1vWkkEGdBCbadaw7qL_bY9gpR0JG_n7Bn/view'),
  ('bengal-coffee-eatery', 'Bengal Coffee & Eatery', 'Ikhsan Irawan', 'ikhsan.irawan@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1QRDJax08OrNFTvkjqCphIIwZ541tYIGu/view'),
  ('anugrah-pancing-sayuran', 'Anugrah Pancing Sayuran', 'Raphael Andreas Handono', 'raphael.handono@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1axwgdGKioPAWFPPqieY173VRDY2qHELl/view'),
  ('fortune-crunch-chicken', 'Fortune Crunch Chicken', 'Muhamad Albi Rayhan Jamaludin', 'muhamad.jamaludin07@gmail.com', 'fnb', NULL, 'https://drive.google.com/file/d/10FH99Em0G12QfcWm1B5OYPh3dT4HwQ-E/view'),
  ('icynom', 'IcyNom', 'Helena Gracia Yunita Simatupang', 'helena.simatupang@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/11xfHxbQ52y9b2kOOkLf7TWMiIrfzXUVm/view'),
  ('lauriel', 'Lauriel', 'Abram Gabriel Sebastian', 'abram.sebastian@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1TcP85QE1zcs_rJqTMvlC7viday84ryZi/view'),
  ('soomoor', 'soomoor', 'dustin liuz', 'dustin.liuz@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/11s6RnBbyQjef4WLshk6IVg2uV011m2Nv/view'),
  ('second-round', 'Second Round', 'Helen Christanti Irata', 'helen.irata@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1G42peexz-1hOZworIq2dyQFtQqnMWkVe/view'),
  ('biullune', 'Biullune', 'shank gentar alam', 'shank.alam@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1g6LwWLnWD6h1eAZ5biw_kgykaHTunf5k/view'),
  ('lamonce-coffee', 'Lamonce Coffee', 'Evelyna Loken Br Surbakti', 'evelyna.surbakti@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1ZyXq0By4YsJKhqFvyl06EWeRLMkWGmDL/view'),
  ('doctorphonestore', 'DoctorPhoneStore', 'michael satrio aryo set', 'Michael.seto@binus.ac.id', 'non_fnb', NULL, 'https://drive.google.com/file/d/1BQyhKt7v00rjmWwxSxqEkapwLIko7kPW/view'),
  ('feelmeal', 'FeelMeal', 'Axlsius Hwoarang', 'axlsius.hwoarang@binus.ac.id', 'fnb', NULL, 'https://drive.google.com/file/d/1faMhRtApK1rlRZhZAfIYz2aGjqNXX7mx/view');

-- ---- Akun penjual (password = NIM ketua) ----
INSERT INTO akun (peran, tenant_id, email, password_hash) VALUES
  ('penjual', (SELECT id FROM tenant WHERE slug='bilbo-lapis-susu'), 'salsabilla.febrihesna@binus.ac.id', '$2y$10$PG3zQfu94hk/CFinIRYyxOypZwSUgEuzSz2aN3ko7F03ssw/4HZ4S'),
  ('penjual', (SELECT id FROM tenant WHERE slug='littleouch'), 'verent.yohan@binus.ac.id', '$2y$10$H2EopmILZRBlyqzZkP2huejVZpqwMrLu4HpWFPyv2QUn53WtOPToC'),
  ('penjual', (SELECT id FROM tenant WHERE slug='fat-al-s-hotdog'), 'shakila.dewi@binus.ac.id', '$2y$10$51t9E4nfgsaUGR58CK4hlO6nwmMKOcY6AKDxa6RwrSOMBaMo56qEu'),
  ('penjual', (SELECT id FROM tenant WHERE slug='wesley-s-heart'), 'akhila.luqman@binus.ac.id', '$2y$10$5lBSrgdzMkfZNblX8GfNq.7/h9pCSsGJ8DEZOZHUEqPWIBA7stGO2'),
  ('penjual', (SELECT id FROM tenant WHERE slug='zelv-re'), 'zelfi.karnilah@binus.ac.id', '$2y$10$O/FUQTB5u3m7rQkzTm7pyO9JduwmN39s0hP1oSrc0FDfwYiDsDJoa'),
  ('penjual', (SELECT id FROM tenant WHERE slug='kopi-jiwapat'), 'kevin.hadiyan@binus.ac.id', '$2y$10$2etERaKjA3dmATK1Xr6jhuq1DKPV2i4Ebxc6kflm4hER.O0M2nRfS'),
  ('penjual', (SELECT id FROM tenant WHERE slug='chrome-petal'), 'azkiya.rabbani@binus.ac.id', '$2y$10$wHPyHRGQrF1mRTjkooUMWe4.OL8pjvVTEobitrC2aUZeNSxeqzE9K'),
  ('penjual', (SELECT id FROM tenant WHERE slug='fresh-laundry'), 'jessica.effendy@binus.ac.id', '$2y$10$mTfybXkMXshd3eIJdoAtxucLeVsjOSQm.UX/pXvttrOdb4626zxrm'),
  ('penjual', (SELECT id FROM tenant WHERE slug='daintsy'), 'bidara.shabira@binus.ac.id', '$2y$10$LemtE./GpLw7kZeB4lHNieLJX1FMvF8Fl8Plf.O27QCJopd7w77sS'),
  ('penjual', (SELECT id FROM tenant WHERE slug='moozy-wear'), 'fayne.firdaus@binus.ac.id', '$2y$10$TPNs5ATZIMAQ9AsCshnEKeNVwTrsOIE7dMU75Fj3ITVom72pNb05u'),
  ('penjual', (SELECT id FROM tenant WHERE slug='so-cool-style'), 'michellie.kwa@binus.ac.id', '$2y$10$/Wz/sZDSAiQ62KKNE/1aVes.NY4F9aFfhVerAB2woMnrN37GJIB7u'),
  ('penjual', (SELECT id FROM tenant WHERE slug='bites-and-drinks'), 'maria.adriellia@binus.ac.id', '$2y$10$Z8u8t9J5sxZv2apinS6Ch.vA/93NSGCGeRRR1JI44p7i9VDKVZYDC'),
  ('penjual', (SELECT id FROM tenant WHERE slug='zavio'), 'elizabeth.rikiyanto@binus.ac.id', '$2y$10$WnXMcva/zAEp8SXmG.724ewANNZBoXXFHMqUMaQs1oQyb/uuOlkH6'),
  ('penjual', (SELECT id FROM tenant WHERE slug='bloobub'), 'ayesha.raditya@binus.ac.id', '$2y$10$giU.De1Nsa1b4d8yEEjjK.ET/VqT1vXD0ABh5sWgN3RByDXnsx4Wa'),
  ('penjual', (SELECT id FROM tenant WHERE slug='cabi'), 'alicia.mulijadi@binus.ac.id', '$2y$10$qKSdzEWnKfaWUPuYwaTVg.v3jeRnNm/R4mxuLP7dITJi15UWaUnUm'),
  ('penjual', (SELECT id FROM tenant WHERE slug='seblak-makwiee'), 'renata.supriadi@binus.ac.id', '$2y$10$KK2gAFpyLvPR5k1yaZGHDONU02v/kr97lY5LnUZv00TQOl5/9lrMG'),
  ('penjual', (SELECT id FROM tenant WHERE slug='mushimushi-studio'), 'clariszya.alexandria@binus.ac.id', '$2y$10$bu34IdOZp3akKsTLMn7KL.hq2hI/L9jJ9SJjMcaW/pxoW2IoAdsdq'),
  ('penjual', (SELECT id FROM tenant WHERE slug='suddenim'), 'raihan.alfarizi@binus.ac.id', '$2y$10$Mrih7ur/YHTQUVOXQwWkuur6w9KOJsDf4hhOo33XpthilyHtdz9oe'),
  ('penjual', (SELECT id FROM tenant WHERE slug='krazzie'), 'amelia.lembong@binus.ac.id', '$2y$10$FdoHTZkxRnk6p8zTIPvy6.iJ0lelq5md3kHJblZIKRy/7YTbemKoy'),
  ('penjual', (SELECT id FROM tenant WHERE slug='kanal'), 'verrill.qabil@binus.ac.id', '$2y$10$LqfTrc8lD6EWr.GPnBmg7ucS9SXgwSwzj7SZoPS.oE8RV/Ham3QU6'),
  ('penjual', (SELECT id FROM tenant WHERE slug='whippory'), 'tatsbita.nabila@binus.ac.id', '$2y$10$jm5xX/bVwenCM1ZCMIR8vuapPZl660PtOAiCU1aIxEGh71xYIy9Om'),
  ('penjual', (SELECT id FROM tenant WHERE slug='beruma-lab-pergantian-dari-army-coffee'), 'jeannifer.kengsiswojo@binus.ac.id', '$2y$10$2D1COva2FgykUsu1yceW8e2qxttkp/wZjyZsZxVPQZYNLZD7yNr2S'),
  ('penjual', (SELECT id FROM tenant WHERE slug='geprek'), 'stephanie.sukmajaya@bi nus.ac.id', '$2y$10$YaTEqPoLOKuUMVS8AtNsROUTFztObPYqerYKUoq5ZrflKuKb0/wB.'),
  ('penjual', (SELECT id FROM tenant WHERE slug='gojie'), 'Zahran.alfadhil@binus.ac.id', '$2y$10$OT6N3SO8z8C/sGP3mD5eRu4EaypylK25s3EIZBJYG9rZpbR2T6Ami'),
  ('penjual', (SELECT id FROM tenant WHERE slug='nexo-sporty'), 'velicia.widjaja001@binus.ac.id', '$2y$10$eMNZPJcrJKvcoLI5oDrMcu3CdXE772WVWzfILbdeBfD8SaNyZDiyu'),
  ('penjual', (SELECT id FROM tenant WHERE slug='fruizzy'), 'mischa.karaseran@binus.ac.id', '$2y$10$gc6G1/5HmahVYCPTuV5OT.XWh95W0AXaiNT6a3nObt0OvR61MZvCa'),
  ('penjual', (SELECT id FROM tenant WHERE slug='neff-footwear'), 'muhammad.latif@binus.ac.id', '$2y$10$95LVYPh2bc6QWcTlGW3Mc.unR95Isbz.vaHm/Sf/w0CSnR4RnELEe'),
  ('penjual', (SELECT id FROM tenant WHERE slug='sandwichu'), 'william.hartono001@binus.ac.id', '$2y$10$wKsW6DQHhzTDL3NRdACpA.E5ZOAUYXUkf3X3hbOOy0YbTOJJOthiO'),
  ('penjual', (SELECT id FROM tenant WHERE slug='doudonails'), 'theresia.sugiwan@binus.ac.id', '$2y$10$jojVOG5kOKWfb8nSsnIyP.fcMscGxSIBYZRzlPN61fkRfjh4Oz8Dm'),
  ('penjual', (SELECT id FROM tenant WHERE slug='semara'), 'albertus.evotianus@binus.ac.id', '$2y$10$vdW2WxPgmQGr5i9Thf6kau9Q39Z0ZxvEVAt3P5DpwFNnKNCEin3vW'),
  ('penjual', (SELECT id FROM tenant WHERE slug='icarus'), 'muhammad.maisan@binus.ac.id', '$2y$10$J4ygx5i7Chg3uZlnWgeK/OwRIUGedFM1LNjybksfTpmx7IOonqUTe'),
  ('penjual', (SELECT id FROM tenant WHERE slug='satis'), 'aura.junia@binus.ac.id', '$2y$10$0xmoOn8Luii.cCuGmpIBSe6c5bdthRJPOxqVjXwc9gfOL0PAgiTHG'),
  ('penjual', (SELECT id FROM tenant WHERE slug='rebiko'), 'annisa.khamilla@binus.ac.id', '$2y$10$86kvlUshfiEw3EHiAs3rDeEhTtiIFMjlc/c0VG0ya5QNNjBhnKV/G'),
  ('penjual', (SELECT id FROM tenant WHERE slug='sai'), 'farrel.athallah@binus.ac.id', '$2y$10$ODGhjTxOTBeBBKvxKj9AkuOSFTN.JB.fl8xfSpmDZYvucozFTcyAS'),
  ('penjual', (SELECT id FROM tenant WHERE slug='kripcau-chips'), 'farel.arrasyid@binus.ac.id', '$2y$10$yq.OwRUTloMNqMe10wq7pekORmdYcCbd.Xd6nZH.Oze7Vig7xniUK'),
  ('penjual', (SELECT id FROM tenant WHERE slug='reactive'), 'irsyal.sanad@binus.ac.id', '$2y$10$HuiCoGbbc2TyDlzhWL8d9uyPXEFP2dqNXfR2t0cdMSSNzGKUP6wfK'),
  ('penjual', (SELECT id FROM tenant WHERE slug='sweetmissu'), 'Okcta.regina@binus.ac.id', '$2y$10$CJ2OUhPl5gtJMv22K8tgfeYscRPlJPGG2zQ3RQJZikbi0aOcGoHda'),
  ('penjual', (SELECT id FROM tenant WHERE slug='june-de-belle'), 'mayra.ayaka@binus.ac.id', '$2y$10$KEb8nCospScNG.mmxDIFoekc46Tvn6HqdG6jY1XkZGrVAZLEgM3yy'),
  ('penjual', (SELECT id FROM tenant WHERE slug='love-live-cake'), 'sivani.salsabbillah@binus.ac.id', '$2y$10$ZeAF6Y6lEsbXtj1QJQUUruR.G0zHDSz4FdNuPgckpDhln70xJMon.'),
  ('penjual', (SELECT id FROM tenant WHERE slug='trinket-tales'), 'fairuz@binus.ac.id', '$2y$10$VssmmzIoQYJTOpFlpjWWCu82rA5dOwj.Y6EHVmAMO2.xHIfCZJA8.'),
  ('penjual', (SELECT id FROM tenant WHERE slug='navie-house'), 'muhammad.aiba@binus.ac.id', '$2y$10$8bL7TTKnKTt4lx4Xn9k/fOCxnK4OeKsO8xRBypjAn76BQM6FzzthW'),
  ('penjual', (SELECT id FROM tenant WHERE slug='sinergi-lestari-mandiri'), 'muhammad.ulya@binus.ac.id', '$2y$10$1DrPn1awQPXKDgCBOEiYBOwOh.CZwnrCguAq/E8joxk6COtTicNnS'),
  ('penjual', (SELECT id FROM tenant WHERE slug='luthena'), 'lusiana.devi@binus.ac.id', '$2y$10$JNpJ3CQsTIy40s3In7Zws./hM0sOPPeuUknAUlm7ngwps7qAFHWRC'),
  ('penjual', (SELECT id FROM tenant WHERE slug='ego-apparel'), 'mohammad.gunawan@binus.ac.id', '$2y$10$JZmkfx4.K7CgciEfjgOG0OIy2rMA.STMdHcVAZT/gqcbCBD56tfRW'),
  ('penjual', (SELECT id FROM tenant WHERE slug='pallas-seafood'), 'muhammad.aladaalah@binus.ac.id', '$2y$10$.oev8eHFmX2y8s8naIhAlOELPllUWDVlMc3piIqqJUT3Rt9mD8Ayu'),
  ('penjual', (SELECT id FROM tenant WHERE slug='chuwink'), 'sharon.hutany@binus.ac.id', '$2y$10$NpZbzKOAFsIrbzqOAA1OT.s.jPF36qPh7GI8y5R6ksaQltS56QVUS'),
  ('penjual', (SELECT id FROM tenant WHERE slug='kriuk-lembu-indonesia'), 'Naufal.annabil@binus.ac.id', '$2y$10$vnZZ1VcoOGZ.0rrUUnbL/OBYzqGDLakT0KNN8tBY0JQbwXIpfhRia'),
  ('penjual', (SELECT id FROM tenant WHERE slug='milzy'), 'shofa.marsandra@binus.ac.id', '$2y$10$U0M/zr2tqn3o8uqyhlJdbejsv7wYO/P9mCRLvx77Zs/zG6eoW3VYi'),
  ('penjual', (SELECT id FROM tenant WHERE slug='macs'), 'moses.amadeus@binus.ac.id', '$2y$10$Gt2C3UbZ9IqH.SKwB/e7C.xre/SmpgAbfFnQTLZzA34K5m1Ox9Hh.'),
  ('penjual', (SELECT id FROM tenant WHERE slug='chomped'), 'nashella.hanzani@binus.ac.id', '$2y$10$o8UQAhUIHJK9jGfSOyPwcey.yzdFQ1GmRkQGUgoYASeFfv394NyOO'),
  ('penjual', (SELECT id FROM tenant WHERE slug='altek-industries'), 'aedil.ismail@binus.ac.id', '$2y$10$GslT3Fba2vUthaaUZlOFNehTrsO99s2cBo8giI3uh7Wu8YxVO8KQi'),
  ('penjual', (SELECT id FROM tenant WHERE slug='the-bliss-c'), 'darius.hosea@binus.ac.id', '$2y$10$pjgJ68uhZkg4/Y2hA82ooO1s4HZhfdSvrTgpsREqoOPvHmhY7DZty'),
  ('penjual', (SELECT id FROM tenant WHERE slug='onzen'), 'michelle.louisa@binus.ac.id', '$2y$10$aLlNWHuiNs.Q0KMHR3PPH.Y0H.iZ4BZFFC9.I.1cfvdydhbXGk4mq'),
  ('penjual', (SELECT id FROM tenant WHERE slug='kiisover'), 'aliyaa.adzany@binus.ac.id', '$2y$10$3SfmryW1lvob94Hf.PPEle24fKoTCDEtmI7W0lAT1k7M6ip76EM2S'),
  ('penjual', (SELECT id FROM tenant WHERE slug='k-r-i-k'), 'caroline.kurniawan@binus.ac.id', '$2y$10$o2QEgE4JIE/sMtji/aq6T.Y767IZARA1px02AVGKR9HfGF6g9UBq.'),
  ('penjual', (SELECT id FROM tenant WHERE slug='backthen'), 'faiza.aliyah@binus.ac.id', '$2y$10$YMpcVcEswxBcoAdrMciQZuH6rRn9YW9ioYzo2nb3ZgpD9Frn70mku'),
  ('penjual', (SELECT id FROM tenant WHERE slug='flor-de-piel'), 'ifan.maulana@binus.ac.id', '$2y$10$IjHsxi0pHp6IAlHNQ3xhme1uEXkYYfqf9LUL865pNauQjbIOXptoy'),
  ('penjual', (SELECT id FROM tenant WHERE slug='aurelune'), 'Ariffin.hermawan@binus.ac.id', '$2y$10$db31KjkbMKrdwivAHihnmOngcD6m3XDXQrs/nO130L7h0LFt6ztJC'),
  ('penjual', (SELECT id FROM tenant WHERE slug='brewchill'), 'calvin.varelly@binus.ac.id', '$2y$10$QhfNCxhnG.n0ux2uQWVgYOrwE8T7XYbZnoXgeFJZ1f63tGAou/OEy'),
  ('penjual', (SELECT id FROM tenant WHERE slug='freddo'), 'michael.suteja@binus.ac.id', '$2y$10$/IYtyNrFTlgLJoQXeLa7KecHXKDADqPZXqIj1bKo2FHcITDd8.ZR.'),
  ('penjual', (SELECT id FROM tenant WHERE slug='mingcase-official'), 'louise.setiahardi@binuus.ac.id', '$2y$10$mHwzjQIUwRbM4i7up/wFAuUBYSO7MVN99/wmF6Si8M65eD9.iuh5i'),
  ('penjual', (SELECT id FROM tenant WHERE slug='creacy-studio'), 'nazwa.inesita@binus.ac.id', '$2y$10$l0.Euo5ThZNMTgTpehhzkOuV/zBDBcaF5Q.PXYk57NHHQ1JHflpDe'),
  ('penjual', (SELECT id FROM tenant WHERE slug='sister-english'), 'widia.sholikha@binus.ac.id', '$2y$10$2PlnNRrT8dqyppSxedwbiegSo3H1fhd1thfbkEOayfVuAah6G0CvW'),
  ('penjual', (SELECT id FROM tenant WHERE slug='pollospok'), 'sean.eros@binus.ac.id', '$2y$10$lR4tqU7rgT1bqaR9PhrYk.1XdpoRZBmjaebN5xlVCyiBl0z.m8ouq'),
  ('penjual', (SELECT id FROM tenant WHERE slug='sera-coffee'), 'reyhaq.muluk@binus.ac.id', '$2y$10$ZHgYT1/Uc0cqj8tbZDKz/.QkSZAI3.sMVm68LuizlZdIgBCO/RCge'),
  ('penjual', (SELECT id FROM tenant WHERE slug='si-madu-koh-siu'), 'kent.zhenoe@binus.ac.id', '$2y$10$h4pMc13XO/9koT408b39oeQ6RciT6NCtId3AHIuXVefAks49JCbLy'),
  ('penjual', (SELECT id FROM tenant WHERE slug='milky-mood'), 'delroy.jefferson@binus.ac.id', '$2y$10$UNgiERlSsd23muTdw34duOkZtPhrzujfATAi0Szky9TRAHPEF0aI6'),
  ('penjual', (SELECT id FROM tenant WHERE slug='harb-coffee'), 'marcel.silap@binus.ac.id', '$2y$10$S9yZXt40S6os6zh83DhtFObjhCjR.KWfSGGPmIYztbHIVY6/MqB6u'),
  ('penjual', (SELECT id FROM tenant WHERE slug='bengal-coffee-eatery'), 'ikhsan.irawan@binus.ac.id', '$2y$10$V6HdD1PA61W.C8XALtq/9uo7zsU8efL49JLVihTAOqe9dfe8h1KWe'),
  ('penjual', (SELECT id FROM tenant WHERE slug='anugrah-pancing-sayuran'), 'raphael.handono@binus.ac.id', '$2y$10$8FgZSNfE6AxDXrVdo1YxyO6Fchw8OQw6jASkBM1u1zU6Tw4dfsX9a'),
  ('penjual', (SELECT id FROM tenant WHERE slug='fortune-crunch-chicken'), 'muhamad.jamaludin07@gmail.com', '$2y$10$S5hq8ahOxZfUQwgK1MFFzeQPFD49awablF8/FS4cLZCH/pJZsuH9a'),
  ('penjual', (SELECT id FROM tenant WHERE slug='icynom'), 'helena.simatupang@binus.ac.id', '$2y$10$71Mfs8wfYYL1VJY3lsNXOem4cWDAlwRIoH9Cs7.C9Qq3tzZQiXSoi'),
  ('penjual', (SELECT id FROM tenant WHERE slug='lauriel'), 'abram.sebastian@binus.ac.id', '$2y$10$bFPD9tVR5sIQBZANye64T.xyvgipssa/r5hiWKf1TlkS0in1u8os2'),
  ('penjual', (SELECT id FROM tenant WHERE slug='soomoor'), 'dustin.liuz@binus.ac.id', '$2y$10$ypPUNk/hJXkHSj6R8uxf/uuZ6y1Eynwaam6f.k8l9NsrJxYbJFJy.'),
  ('penjual', (SELECT id FROM tenant WHERE slug='second-round'), 'helen.irata@binus.ac.id', '$2y$10$d.z1zOqsB9.LQpB.yFJHP.VEiFiDNLzCwUjacmaLqANAOtQPcsZN2'),
  ('penjual', (SELECT id FROM tenant WHERE slug='biullune'), 'shank.alam@binus.ac.id', '$2y$10$A3.YfkH1oXUj.xQlB30nFOqT0CCwVNlGvz04vL46LoEtfnsLT5CIW'),
  ('penjual', (SELECT id FROM tenant WHERE slug='lamonce-coffee'), 'evelyna.surbakti@binus.ac.id', '$2y$10$PFmjBebIxiRJN7BytQdCueN97FGzIjPjcbmEaLOdehmSBRq87Duv6'),
  ('penjual', (SELECT id FROM tenant WHERE slug='doctorphonestore'), 'Michael.seto@binus.ac.id', '$2y$10$xS.OrKweLqriTuexP3e7p.0dNOmZlM7ujs4xL.VCuWiRmDa8Qn/xG'),
  ('penjual', (SELECT id FROM tenant WHERE slug='feelmeal'), 'axlsius.hwoarang@binus.ac.id', '$2y$10$sePSH/z5yzQzro6MfhfvDus.MkNjbjmt9I0AU.B/cceafMxjhDake');

-- ---- Admin password -> 'adminmanawa' ----
UPDATE akun SET password_hash = '$2y$10$qBFPRtbT5r4KcOg3l8z56u6D0DT8s1KiDJj.FGRZroNiU5hKGFdCi' WHERE email = 'admin@manawa.id';

